## Write a Numpy program to compute the multiplication of two given matrixes

In [11]:
import numpy as np
p = np.array(([1,0],[0,1]))
q = np.array(([1,2],[3,4]))
print("original matrix:")
print(p)
print(q)
print('The mul')
c=p.dot(q)
print(c)

original matrix:
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]
The mul
[[1 2]
 [3 4]]


## Write a NumPy program to compute the determinant of a given square array

In [25]:
a=np.array(([1,0],[0,1]))

c=np.linalg.det(a)
print(c)

1.0


## Write a NumPy program to compute the cross product of two given vectors

In [17]:
a=np.array(([1,0],[0,1]))
b=np.array(([1,2],[3,4]))
c=np.cross(a,b)
print(c)

[ 2 -3]


## Write a NumPy program to compute the condition number of a given matrix

In [21]:
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
c=np.linalg.cond(a)
print(c)

1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [24]:
a = np.array(([1,2],[3,4]))
c=np.linalg.inv(a)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]
